### ISSUE TITLE
[Bug]: Blank page in ubuntu 16.04

### ISSUE THREAD

**Issue by simplemx** [djyde/koy#16]
node-version:  v8.11.3

After running `koy README.md`, the preview window show a blank page with empty body content

**Comment by djyde** [comment]
I don't have Ubuntu device. Could you please open dev tool and capture the log?

**Comment by Leedehai** [comment]
My macOS terminal reported an error before opening a blank page:
```
TypeError: app.exposeObject is not a function
    at main (/usr/local/lib/node_modules/koy/bin/index.js:30:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
node version: v8.12.0
koy version: koy@0.0.9

**Comment by djyde** [comment]
Oops, this is because Carlo has removed the `exposeObject` API. I will fix it later.

cc @egoist

**Comment by simplemx** [comment]
@djyde dev tool show no log at all and so is my terminal. I think some dependencies has compatibility problem with my os.

**Comment by djyde** [comment]
@simplemx Did your terminal show `TypeError: app.exposeObject is not a function`?

**Comment by simplemx** [comment]
@djyde Sorry, yesterday I use a very old version of chrome(59.*) and no message show in terminal, after upgrade to newest version and it show as follow:
```
TypeError: app.exposeObject is not a function
    at main (/home/simplemx/applications/node-v10.13.0-linux-x64/lib/node_modules/koy/bin/index.js:30:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by djyde** [comment]
@simplemx Awesome. I will fix it. But the new RPC API makes me confused. Feel free to PR ❤️
